### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by mcroni** [mahart-studio/kivystudio#18]
something seems to break the program on this execution `on_size: Clock.schedule_once(lambda dt: setattr(self, 'grid_len', int(self.width/(self.children[0].width+10))), 1)` .

**Comment by avour** [comment]
What is the attr 'grid_len'

**Comment by mcroni** [comment]
it is part of the code i pulled,maybe you added it

**Comment by mcroni** [comment]
the recursion seems to come from here ``self.screen.bind(scale=lambda *args: setattr(self.screen, 'center', self.center))``

**Comment by avour** [comment]
Ya i see where the issue is beneath this line the recursion seems to come from here self.screen.bind(scale=lambda *args: setattr(self.screen, 'center', self.center))
you should remove  self.bind(center=self.screen.setter('center')) they are making to many calls which is causing a recursion error in python3 i am currently testing with 2

**Comment by mcroni** [comment]
Removing that prevents the emulator to work,

**Comment by avour** [comment]
i was checking the logs turns out @Solomon1999 fixed this issue at commit 95248dfc96cdc6cb6fb5daff092c8c68d780894d , all he did was remove the line self.screen.bind(scale=lambda *args: setattr(self.screen, 'center', self.center))
in 'component/emulator_area/__init__.py'

**Comment by mcroni** [comment]
but the emulator doesnt work anymore

**Comment by avour** [comment]
what problem does it show now

**Comment by mcroni** [comment]
it doesnt show any error now

**Comment by mcroni** [comment]
realized from the video you uploaded an action called auto emulation which is above the set file for emulation which isnt available in the latest build here. Clicking on the set file for emulation doesnt tick the file either, are you working on a separate branch, probably this is what is causing the issues

**Comment by avour** [comment]
Yeah the current local branch i'am working, is where I added the tick stuff and i haven't merge with master because it isn't done yet.
Sorry for the inconvenient will try to fix it now

**Comment by avour** [comment]
And by the have you see the to-do list you requested for?

**Comment by mcroni** [comment]
yeah seen the to do list, cant get past this error , will start working on it when we fix this issue

**Comment by avour** [comment]
Done with the branch, i hope this fixes the issue
