### ISSUE TITLE
error os.getlogin()

### ISSUE THREAD

**Issue by juanjavatus** [mahart-studio/kivystudio#26]
hi,
I am getting the following error running main.py:

   File "../kivystudio/widgets/filemanager/__init__.py", line 65, in get_defualt_user_dir
     username = os.getlogin()
 FileNotFoundError: [Errno 2] No such file or directory

Regards

**Comment by mahart-studio** [comment]
This should be fixed now,
try to pull now

**Comment by juanjavatus** [comment]
I solved with this:
username = getpass.getuser()
thanks for your answer
Regards

**Comment by brunobrown** [comment]
For me it worked like this:

In "filemanager/__init__.py", on line 67, change from:
`username = os.getlogin()`
for:
`username = getpass.getuser()`

---

Also modify the method "open(self, *largs):" on line 37 of the "modal_cursor.py" file to:

`def open(self, *largs):`
          `# self._window = self._search_window()`
          `# if not self._window:`
          `#     Logger.warning('ModalView: cannot open view, no window found.')`
          `#     return`
          `if self.parent:`
                  `self.parent.remove_widget(self)`
              `Window.add_widget(self)`
