### ISSUE TITLE
Non functioning download link

### ISSUE THREAD

**Issue by mcroni** [mahart-studio/kivystudio#6]
The download link to kivy studio doesnt work https://mahartstudio.com/kivystudio

**Comment by me2beats** [comment]
same problem

**Comment by avour** [comment]
Yeah, the download link doesn't work because its still under tight development and  has no releases yet,
and if you guys would like to contribute, we would love a Pull Request....
Thanks in advances.

**Comment by mcroni** [comment]
Cloned the repo but can't get it to work,
