### ISSUE TITLE
No module named 'kivystudio'

### ISSUE THREAD

**Issue by me2beats** [mahart-studio/kivystudio#7]
Got this error when trying to run main.py
```
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from kivystudio.tools import iconfonts
ModuleNotFoundError: No module named 'kivystudio'
```
what did I miss?

**Comment by me2beats** [comment]
ok never mind

**Comment by avour** [comment]
I see you've solved it, but for future reference you need to been on that directory before running the 'main.py'

**Comment by brunobrown** [comment]
test

**Comment by brunobrown** [comment]
For me it worked like this:

In "filemanager/__init__.py", on line 67, change from:
`username = os.getlogin()`
for:
`username = getpass.getuser()`

---

Also modify the method "open(self, *largs):" on line 37 of the "modal_cursor.py" file to:

`def open(self, *largs):`
          `# self._window = self._search_window()`
          `# if not self._window:`
          `#     Logger.warning('ModalView: cannot open view, no window found.')`
          `#     return`
          `if self.parent:`
                  `self.parent.remove_widget(self)`
              `Window.add_widget(self)`
